### ISSUE TITLE
Metoda isInside(Point2D point) dla RoadModel

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/CrossroadsManager#4]
Napisać metodę sprawdzającą czy zadany punkt znajduje się na drodze. Można też dodać przeciążoną z dodatkowym parametrem mówiącym o numerze pasa, ponieważ będzie nas bardziej interesowało, czy samochód znajduje się na prawym pasie drogi, przed światłami, niż czy jest na niej w ogóle.

**Comment by olafkrawczyk** [comment]
Patrząc na atrybuty RoadModel wydaje mi się, że najlepszym rozwiązaniem będzie zmiana atrybutów z VERTICAL i HORIZONTAL na NORTH, EAST, SOUTH, WEST. Tym sposobem o wiele łatwiej będzie nam wyznaczyć czy dany punkt znajduje się na drodze oraz unikniemy podawania ujemnych wartości przy tworzeniu dróg dla skrzyżowania.
![image](https://cloud.githubusercontent.com/assets/9090094/24677017/91191072-1985-11e7-899c-427e6019b898.png)
