### ISSUE TITLE
Zaimplementować sposób zauważania świateł przez samochody.

### ISSUE THREAD

**Issue by majcherpiotrek** [piotrmajcher94/CrossroadsManager#7]
Czy samochody będą jakoś same to rozpoznawały?
Wtedy można tak:
-dodać informację o światłach do drogi
-samochód będzie sprawdzał na której jest drodze
-jak zobaczy czerwone to zatrzymywał się jak dojedzie do linii
(W takim rozwiązaniu może być problem z najeżdżaniem na siebie samochodó)

Sposób z managerem ruchu:
-Klasa, która kontrolowałaby z góry ruch wszystkich samochodów w zależności od świateł, 
mogłaby wtedy też kontrolować zderzenia

**Comment by olafkrawczyk** [comment]
http://stackoverflow.com/questions/34113327/javafx-check-current-position-of-pathtransition-while-running

Spoko przykład jak wykrywać kolizje wykorzystując transitions
Możemy wykorzystać to na dwa sposoby. Pierwszy - wykrywanie kolizji z przedmiotami (sygnalizacja, inne samochody) przed samochodem. Wersja druga: wykrywanie kolizji za pomocą managera, który w przypadku zmiany świateł zatrzyma wszystkie samochody w kolejce.
